name: Keep Glitch Alive

on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/5 * * * *'  # Ping every 5 minute

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Glitch App
        run: curl -s "https://catnip-highfalutin-treatment.glitch.me" >/dev/null
