name: Keep Glitch Alive
on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute
  workflow_dispatch:  # Allows manual triggering
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Glitch
        run: curl -s "https://bristle-east-coin.glitch.me"
